name: Scrape OutdoorLads Events

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch: {}

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests beautifulsoup4

      - name: Run scraper
        run: python outdoorlads_scraper.py

      - name: Upload CSV file as artifact
        uses: actions/upload-artifact@v4
        with:
          name: outdoorlads-events
          path: events.csv

      - name: Commit files back to repo
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"
          git add events.csv
          git commit -m "Updated events data" || echo "No changes to commit"
          git push origin HEAD:main
