name: Scrape OutdoorLads Events

on:
  schedule:
    - cron: '0 * * * *'  # Every hour
  workflow_dispatch: {}  # Manual trigger

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4

      - name: Run scraper
        run: |
          python outdoorlads_scraper.py

      - name: Commit updated data
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"
          git add odl_events.json || echo "No odl_events.json to add"
          git commit -m "Update event data" || echo "No changes to commit"
          git push origin HEAD:main
