name: Scrape OutdoorLads Events

on:
  # Run automatically every day at 05:00 UTC (adjust as needed)
  schedule:
    - cron: '0 5 * * *'

  # Allow manual triggering from the GitHub Actions tab
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest # Use the latest Ubuntu runner

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4 # Use the latest checkout action

      - name: Set up Python
        uses: actions/setup-python@v5 # Use the latest Python setup action
        with:
          python-version: '3.10' # Specify Python version (adjust if needed)

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper
        run: python outdoorlads_scraper.py

      - name: Upload results as artifact
        uses: actions/upload-artifact@v4 # Use the latest upload artifact action
        with:
          name: outdoorlads-events-csv # Name of the artifact zip file
          path: outdoorlads_events.csv # Path to the file to upload
          if-no-files-found: error # Optional: Fail step if CSV is not generated
